monolog:
    handlers:
        security:
            # log all messages (since debug is the lowest level)
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/security.%kernel.environment%.log'
            channels: [security]
            max_files: 7
        mailer:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/mailer.%kernel.environment%.log'
            channels: [mailer]
            max_files: 7
        request:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/request.%kernel.environment%.log'
            channels: [request]
            max_files: 7
        doctrine:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/doctrine.%kernel.environment%.log'
            channels: [doctrine]
            max_files: 7
