App\Entity\Address:
    constraints:
        - App\Validator\Address:
    properties:
        country:
            - NotBlank: ~
            - Country: ~
        locality:
            - NotBlank: ~
            - Valid: ~
        streetName:
            - NotBlank: ~
