App\Entity\ExternalAssessmentCategory:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [category, scale, sequence, externalAssessment]
            message: sequence_category_scale
    properties:
        category:
            - NotBlank: ~
            - Length:
                max: 50
        externalAssessment:
            - NotBlank: ~
            - Valid: ~
        scale:
            - NotBlank: ~
            - Valid: ~
        sequence:
            - NotBlank: ~
