App\Entity\ExternalAssessmentField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, category]
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 50
        category:
            - NotBlank: ~
            - Length:
                max: 50
        yearGroups:
            - Valid: ~
