App\Entity\ExternalAssessmentField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, externalAssessmentCategory]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [externalAssessmentCategory, sequence]
            message: sequence_category_scale
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 50
        yearGroups:
            - Valid: ~
            - NotBlank: ~