App\Entity\Family:
    properties:
        relationships:
            -   Valid: ~
        name:
            - NotBlank: ~
        nameAddress:
            - NotBlank: ~
        languageHomePrimary:
            - NotBlank: ~
            - Language: ~
        languageHomeSecondary:
            - Language: ~
