App\Entity\FamilyRelationship:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [family,adult,child]
    properties:
        relationship:
            - NotBlank: ~
        family:
            - NotBlank: ~
        adult:
            - NotBlank: ~
        child:
            - NotBlank: ~
