App\Entity\House:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, nameShort]
            message: validation.duplicate
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 30
        nameShort:
            - NotBlank: ~
            - Length:
                max: 4
        logo:
            - App\Validator\Logo: ~
