App\Entity\Person:
    properties:
        personalBackground:
            - App\Validator\BackgroundImage: ~
        photo:
            - Image:
                maxRatio: 0.95
                minRatio: 0.625
                allowLandscape: false
                allowSquare: false
                maxSize: 750k
        officialName:
            - NotBlank: ~
        preferredName:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        email:
            - Email: ~
            - App\Validator\PersonEmail:
                errorPath: email
        emailAlternate:
            - Email: ~
            - App\Validator\PersonEmail:
                errorPath: emailAlternate
