App\Entity\PersonRole:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [name]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [nameShort]
    properties:
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
            - Length:
                  max: 4
