App\Entity\PersonField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [name]
    properties:
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~
